- cltk/stem/latin/syllabifier.py
- cltk/tests/test_cltk.py
- docs/latin.rst
Including the Latin syllabifier in the stem module, based on the original work of Fr. Matthew Spencer.
> Latin syllabifier, tests, and doc

- docs/installation.rst
> Fix inline monospace styling typo in installation docs

- cltk/reuse/levenshtein.py
Some initial thinking about what this feature might look like. I think that the text reuse module can get more complex as we research more and interesting ways to compare documents in classical languages.
> Add levenshtein distance calculation for simple and tokenized sentence ratios

- cltk/text_reuse/comparison.py
- cltk/text_reuse/text_reuse.py
- contributors.md
Previous csv_output errors are resolved and tested--thanks, @kylepjohnson!
> Add ability to set metadata on TextReuse and Comparison classes

- cltk/corpus/utils/formatter.py
Fixes https://github.com/cltk/cltk/issues/114
> Improve PHI5 cleanup

- cltk/corpus/sanskrit/corpora.py
- cltk/corpus/utils/importer.py
Hello,
I have added a sanskrit corpus in cltk. Please review my change and let me know if it is ok.
Thank you.
Regards,
Md. Sabbir Alam
> added corpora for classical sanskrit

- cltk/corpus/sanskrit/corpora.py
- cltk/corpus/utils/importer.py
> Revert "added corpora for classical sanskrit"

- cltk/utils/philology.py
- setup.py
Changed sorted(tokens) to sorted(tokens, key=coll.sort_key) according to the pyuca rules.
and added pyuca to the install_requires key in setup.py.
> changed sort according to pyuca rules.

- cltk/corpus/chinese/corpora.py
The repo containing the xml files is [here](https://github.com/nishnik/chinese_text_cbeta_taf). Kindly fork it as I think I won't be able to transfer it due to lack of admin rights.
Ref #144
> Added CBETA_taf corpus

- cltk/__init__.py
> Added metadata

- cltk/corpus/chinese/corpora.py
Repo [here](https://github.com/cltk/chinese_text_cbeta_txt)
> Added the cbeta txt corpora

- cltk/corpus/greek/alphabet.py
added alphabets list for Greek Corpus  #62
> added alphabets in Greek Corpus

- cltk/corpus/greek/corpora.py
The pull request adds Lacus Curtius Greek corpora to CLTK.
Fixes https://github.com/cltk/cltk/issues/49
> ENH: Added Lacus Curtius Greek Corpora for CLTK

- cltk/corpus/greek/tlg/parse_tlg_indices.py
- cltk/tests/test_corpus.py
issue #103 
Modified all methods and added corresponding tests.
> Added functions to handle author_date.json for TLG

- README.md
Clausulae analysis is an integral part of Greek and Latin prosimetrics. This class analyses the prosody produced by the scanner class and returns a dictionary in which each key is a type of clausula and each value is the frequency of that clausula in the supplied prosody.
The list of clausulae that the class looks for is derived from the list provided in John Ramsey's Cambridge commentary of Cicero's First and Second Philippic.
> Clausulae Analysis Class

- cltk/corpus/latin/corpora.py
- cltk/tests/test_corpus.py
Added the corpus entry and the test for the same
Can be merged after the transfer of repo
https://github.com/aakarshsingh/latin_text_antique_digiliblt
> Request to Merge Antique Latin from digilibLT

- cltk/tests/test_tokenize.py
- cltk/tokenize/word.py
Resubmitting pull request with fixed indentation and with missing assignment added.
> Update Latin tokenizer to handle '-n'

- cltk/corpus/latin/corpora.py
The Patch adds Grammaticorum Latinorum Corpus to CLTK.
Fixes https://github.com/cltk/cltk/issues/47
> Added Grammaticorum Latinorum to CLTK

- README.md
- cltk/corpus/utils/importer.py
- cltk/tests/test_corpus.py
- Added progress information for download of data (printing to sys.stdout for the time being)
- Added CorpusImportError exception class, since there are many different things that can go wrong when importing corpora and I think it makes sense to report all these problems with a more specific error than an assertion error.
- Replaced check_corpus_availability with get_corpus_properties since the function returns properties and added an extra check.
- Added tests to ensure that CorpusImportError is indeed raised in the cases checked.
> Progress for CorpusImporter

- cltk/corpus/sanskrit/itrans/itrans_transliterator.py
- cltk/corpus/sanskrit/itrans/unicode_transliterate.py
- cltk/tests/test_corpus.py
- docs/sanskrit.rst
This looks a lot better. I think there was some error in the previous one.
I too was surprised to see that they couldn't be automatically merged.
> Added docs and tests for Sanskrit transliterators

- cltk/corpus/telugu/corpora.py
- docs/index.rst
- docs/telugu.rst
- Added <code>/cltk/corpora/telugu/</code>
- Added <code>/docs/telugu.rst</code>
- Updated <code>/docs/index.rst</code>
Did I miss anything ? Thank you.
> Added telugu

- cltk/tests/test_utils.py
- cltk/utils/file_operations.py
Pull request for changes as suggested in #283
> add function to create cltk paths

- cltk/corpus/punjabi/alphabet.py
With reference to the #320, I created the alphabet.py script which contains the lists of the alphabets of the language
> Add Punjabi Module, Add alphabets

- docs/punjabi.rst
Added docs file, but it just contains the brief description what is done i.e. alphabets are added and numerifier added, and will be updated as the new features are added to the module
> Add docs/punjabi.rst

- cltk/corpus/punjabi/corpora.py
- cltk/corpus/utils/importer.py
- cltk/tests/test_corpus.py
Adding the support to import the corpus of cltk/punjabi_text_gurban and add corresponding test
> Punjabi text gurban

- cltk/tests/test_text_reuse.py
- cltk/text_reuse/comparison.py
This PR is related to Issue #322
> ENH: Added minhash function

- cltk/corpus/old_english/corpora.py
- cltk/corpus/utils/importer.py
The Pull Request is related to Issue #225
> Add corpus for Old English

- docs/multilingual.rst
The patch add the documentation related to the String Comparison function added in Issue #322
> DOC: Add docs entry for String Comparison

- cltk/exceptions.py
- cltk/stem/latin/declension.py
- cltk/tests/test_stem.py
- contributors.md
- docs/latin.rst
- Second answer to issue #385
- Added cltk.step.latin.declension
- Added cltk.exceptions. This could be moved around but my feeling was that having a central module for exception would ensure "stability" across the codebase.
> Added CollatinusDecliner : provides a declining tool for Latin

- cltk/corpus/latin/corpora.py
> ENH: Add Poeti d'Italia corpus

- docs/multilingual.rst
> Add Damerau-Levenshtein algorithm

- cltk/corpus/prakrit/corpora.py
- cltk/corpus/utils/importer.py
Referring to #424 
Please advise if any more changes needed.
> added prakrit gretil corpora

- docs/bengali.rst
* The Indian Tokenizer successfully tokenizes Bengali sentences. The Documentation should be updated to reflect the same 
* Example sentence should be a part of the Ancient or Medieval linguistics. 
@kylepjohnson kept all of the above in this pull request. Previous PR closed due to coverage tests failing due to the recent Pull Request adding alphabet.py under the Hindi section.
> Update Bengali Documentation to include the Tokenizer

- cltk/stem/akkadian/syllabifier.py
- cltk/tests/test_stem.py
Not sure if this 100% the right way to do it.  I tried to copy the structure and format of the Latin syllabifier.  I was not able to run the tests in Pycharm as I'm unsure how to get it to import the local version of cltk, vs. the system installed one.  So each time I ran the tests it was unable to import my new module.  I was able to run some simple tests of my own by loading the module from the terminal and manually testing the function.
> Added Akkadian syllabifier and test.

- docs/sanskrit.rst
> Updated Sanskrit.rst

- cltk/phonology/akkadian/stress.py
- cltk/tests/test_phonology.py
The code should be all good, not sure exactly what's happening with Github's pull request, but the total diff looks clean.  This is just a small function to find stress in an Akkadian word.  I wrote the test as well.
> Stress finder for Akkadian

- docs/old_english.rst
Issue #456 addressed for Old English language.
> #456 old_english.rst updated

- docs/middle_english.rst
Issue #456 addressed for Middle English language.
> #456 middle_english.rst updated

- docs/greek.rst
Issue #456 addressed for Greek language.
> #456 greek.rst updated

- docs/coptic.rst
Issue #456 addressed for Coptic language.
> #456 coptic.rst updated

- docs/chinese.rst
Issue #456 addressed for chinese language. Please review.
> #456 chinese.rst updated.

- docs/javanese.rst
Issue #456 addressed for Javanese language.
> #456 Javanese doc updated

- docs/tibetan.rst
Issue #456 addressed for Tibetan language.
> #456 tibetan.rst updated

- docs/latin.rst
Issue #456 addressed for Latin language.
> #456 Latin doc updated.

- docs/malayalam.rst
Issue #456 addressed for Malayalam language.
> #456 Malayalam doc updated.

- docs/punjabi.rst
Issue #456 addressed for Punjabi language.
> #456 Punjabi.rst updated

- docs/hindi.rst
Issue #456 addressed for Hindi Language.
> #456 Hindi doc updated.

- docs/prakrit.rst
Signed-off-by: Ashutosh Saboo <ashutosh.saboo96@gmail.com>
Hi @kylepjohnson . Kindly review this PR for **Prakrit** . This completes the doc for Prakrit in #456 .
Thanks.
> Added complete doc for Prakrit

- cltk/corpus/persian/alphabet.py
- cltk/corpus/urdu/alphabet.py
Added alphabets+digits for Urdu language
> Added alphabet.py for Urdu

- docs/telugu.rst
> Added info about tokenizer for telugu language

- cltk/corpus/old_norse/corpora.py
added key "location" in the OLD_NORSE_CORPORA
> small change

- cltk/corpus/arabic/alphabet.py
- docs/arabic.rst
I have added alphabet and docs for Arabic as discussed in issue #517 .
> Added alphabet and docs for Arabic

- docs/latin.rst
Docs for TrainLemmatizer and ContextLemmatizer.
> Update Backoff Lemmatizer Docs

- cltk/tests/test_tokenize.py
- cltk/tokenize/sentence.py
Also, sentence tokenizer test has been updated to include a wider variety of punctuation.
> Fixes #531, re: exclamation in sentence tokenizer

- docs/akkadian.rst
- docs/ancient_egyptian.rst
Here's an update to the Akkadian documentation with all new methods.
Also fixed a small spelling error.
> Added to Akkadian documentation.

- cltk/corpus/kannada/alphabet.py
Kannada alphabet.py file added!
> Added Kannada Language

- cltk/corpus/old_swedish/corpora.py
- cltk/phonology/utils.py
- docs/old_norse.rst
- docs/old_swedish.rst
Add the Swedish corpus available at https://github.com/cltk/old_swedish_texts
> Old swedish corpus

- cltk/prosody/old_norse/verse.py
- cltk/tests/test_languages/test_old_norse.py
- docs/old_norse.rst
- setup.py
* VerseManager -> MetreManager
* Added a new method to MetreManager -> load_poem_from_paragraphs. It can guess if it is a specific metre or just a list of stanzas.
* Added UnspecifiedStanza class to process unknown metres.
* Docs and test are updated.
> Small update for Old Norse poetry

- cltk/corpus/old_norse/corpora.py
- docs/old_norse.rst
I add the Old Norse dictionary here so that CorpusImporter can be used to import this.
Creation and use of the dictionary present here https://github.com/cltk/old_norse_dictionary_zoega.
> Old norse dictionary

- docs/kannada.rst
Just changed the formatting to be consistent.
> Simple formatting change

- docs/development.rst
- docs/installation.rst
- src/cltk/tag/pos.py
Previously, in the `cltk.tag.pos` module, the various NLTK-based trained models were loaded on each invocation of a `tag_xxx` method, resulting in growing memory consumption.
Now these models are memoized in the _instance_ of `POSTag`.
> memoized the loading of modules in the tag module

- src/cltk/languages/pipelines.py
Forgot to add ner to the old english pipeline
> add ang ner to pipeline

- src/cltk/wordnet/wordnet.py
> Fixes issue #1052

- notebooks/CLTK Demonstration.ipynb
- notebooks/CLTK data types.ipynb
- notebooks/Demo of Pipeline for all languages.ipynb
- notebooks/Make custom Process and add to Pipeline.ipynb
- pyproject.toml
- src/cltk/nlp.py
- src/cltk/tag/treebanks.py
> Print invoked pipeline

- src/cltk/phonology/grc/transcription.py
replace spacing diaeresis with combining diaeresis (x306)
> fix regex bug causing vowel with diaeresis (ϋ ϊ) to be deleted

- poetry.lock
- src/cltk/sentence/lat.py
- src/cltk/tokenizers/lat/lat.py
replacement for https://github.com/cltk/cltk/pull/1091 with commits squashed for good form.
Tests pass:
```fish
python tests/test_tokenize_and_sent.py                                                         4957ms  Mon 12 Apr 2021 21:06:21 BST
.......................
----------------------------------------------------------------------
Ran 23 tests in 2.919s
OK
```
> use class instance as now property

- poetry.lock
- pyproject.toml
- src/cltk/core/data_types.py
- src/cltk/dependency/stanza.py
- src/cltk/embeddings/processes.py
- src/cltk/embeddings/sentence.py
- src/cltk/ner/ner.py
- src/cltk/utils/file_operations.py
- src/cltk/utils/utils.py
Take a look? No logic was changed. A few expressions expanded and variable names made more explicit.
> add type annotations, light refactor

- poetry.lock
- pyproject.toml
https://github.com/cltk/cltk/issues/1157
Will wait on build server
> Update scikit to v1

- README.rst
Let CLTK be more social by adding a link to the Twitter account and the Discord server.
> Add shields to README.rst 

- pyproject.toml
- src/cltk/alphabet/grc/grc.py
Update LOWER_DIARESIS_GRAVE and LOWER_DIARESIS_CIRCUMFLEX lookup tables
> Update Diaeresis Lookup Tables

- .gitignore
- notebooks/CLTK Demonstration.ipynb
- pyproject.toml
- src/cltk/dependency/processes.py
Also includes updated demonstration nb
> Update vers 126 for master
