cltk/cltk

cltk/tokenize/word.py

- Handles: -que, -ne, -ue/-ve, -cum
- Includes expanded and better organized list of exceptions
- Prepends '-' (hyphen) to separated enclitics to better mark them in returned list, e.g. 'arma virumque' > ['arma','virum','-que']

Fix handling of enclitics in word tokenizer

---

cltk/corpus/latin/phi/phi_authors_works.json

Don't know it this is useful, I processed every .idt file of phi and made a dictionary with id label (LAT0023) as key and {"author":"name", "works":["work1", "work2"]}.
Please see if it's ok or a better structure is needed

Added phi index with authors and works

---

cltk/corpus/latin/phi/phi_index.json

Fixed beta codes in strings used to encode editorial signs like "[" and "]"

fixed beta codes in strings, mostly [2 and ]2 to [ and ]

---

cltk/tests/test_tokenize.py
cltk/tokenize/word.py

Minor edit to Latin tokenizer—took 'neque' out of exceptions list, so that it tokenizes as:
'neque' > ['ne', 'que']
This follows the practice of Perseus NLP data.
Also, updated the corresponding test.

Update Latin tokenizer to handle 'neque'

---

cltk/tests/test_tokenize.py
cltk/tokenize/word.py

Minor tweak—the tokenizer finds/replaces 'nec' with ['c', 'ne'] before looking at other enclitics/etc. Seemed easier to handle as a special case rather than try to match on final 'c'. Let me know if anyone thinks of a better way to handle this.

Update Latin word tokenizer to handle 'nec' 

---

dev-requirements.txt

`dev-requirements.txt` used to specify the codecov install version as 1.6.4, but the latest version is 1.6.3.

chore: rollback codecov version from 1.6.4 to 1.6.3

---

cltk/prosody/latin/scanner.py

The anceps code fails on sentences that are only one character long (often chapter numbers), so this fixes that issue.

Fixed index error in Latin prosody code

---

CONTRIBUTING.md
README.md

I wrote up a quick tutorial to help prospective contributors set up a dev environment and install cltk from source. also, I'm a bit dubious about including `cltk==0.1.32` in `dev-requirements.txt`. If you're doing development, you should be installing the bleeding edge version from github from source instead of getting the pip version? I'm not sure if they would conflict at all, but it could be a possibility.

[MRG] doc: add tutorial for installation of dev version

---

cltk/tests/test_tokenize.py
cltk/tokenize/word.py

Minor update—Latin tokenizer now handles 'sodes' & 'sultis'. Handled for now like 'nec', i.e. as an exception using list comprehensions before handling other enclitics. Will rewrite this to be more efficient, using an if block.

Update Latin word tokenizer to handle more contractions

---

cltk/tests/test_tokenize.py
cltk/tokenize/word.py

Testing some sentences this morning, I realized that the tokenizer was for the most part only looking at lowercase tokens. This update makes it so that the tokenizer tests lowercase tokens but, if the original token was uppercase, maintains the case in the new token that contains the first letter of the original token. So:
'Verumst' > ['Verum', 'est']
'Mecum' > ['cum', 'Me']

Uppercase handling in Latin tokenizer

---

CONTRIBUTING.md

quick fix for the formatting of the code blocks in CONTRIBUTING.md, which had unnecessary spacing before.

doc: fix code blocks in contributing docs

---

README.md

Removed link to file which was removed in a previous commit. 
Reference: https://github.com/cltk/cltk/commit/2527ded7d04017f953a99defe1b4232dc070c01f

README: Updated Contributing block

---

cltk/corpus/sanskrit/corpora.py
docs/sanskrit.rst

Added sanskrit parallel corpus([srimad-bhagavadgita](http://www.gitasupersite.iitk.ac.in/srimad?language=dv&field_chapter_value=1&field_nsutra_value=1) and [valmiki-ramayana](http://www.valmiki.iitk.ac.in/)) from <a href="http://www.gitasupersite.iitk.ac.in/">gitasupersite</a>.
- Corresponding repository : <a href="https://github.com/cltk/sanskrit_parallel_gitasupersite">/cltk/sanskrit_parallel_gitasupersite</a>

Added sanskrit_parallel_gitasupersite

---

cltk/corpus/sanskrit/corpora.py
docs/sanskrit.rst

Added sanskrit monolingual corpus([srimad-bhagavadgita](http://www.gitasupersite.iitk.ac.in/srimad?language=dv&field_chapter_value=1&field_nsutra_value=1) and [valmiki-ramayana](http://www.valmiki.iitk.ac.in/)) from <a href="http://www.gitasupersite.iitk.ac.in/">gitasupersite</a>.
- Corresponding repository : <a href="https://github.com/cltk/sanskrit_text_gitasupersite">/cltk/sanskrit_text_gitasupersite</a>
- Added scrappers(<a href="https://github.com/cltk/sanskrit_text_gitasupersite/blob/master/bhagavadgita/scrape.py">bhagavadgita</a> and <a href="https://github.com/cltk/sanskrit_text_gitasupersite/blob/master/ramayana/scrape.py">ramayana</a>) as well.

Added sanskrit_text_gita_supersite

---

cltk/stem/lemma.py

Replaced unix file separators (slashes) so os.path.join joins the entire path with OS native separators.

Fixed path bug in Windows

---

cltk/corpus/latin/__init__.py

Using the Latin Library corpus as a test case, this feature allows
you to refer to a corpus and load it with PlaintextCorpusReader using
the following syntax:
from cltk.corpus.latin import latinlibrary
The code checks to make sure that a corpus is installed in the
main CLTK_DATA and raises an error if it is not there.

Add feature to load Latin corpora directly using PlaintextCorpusReader

---

cltk/corpus/latin/__init__.py
cltk/tests/test_tokenize.py
cltk/tokenize/word.py

Updates to the Latin tokenizer including:
- Adding hyphen before enclitics to better distinguish them from other forms
- Reverse the order of tokenized enclitics (i.e. place them after word rather than before)
- Stop tokenizing 'neque'/'nec' (see https://github.com/PerseusDL/treebank_data/issues/8)
- Better handle case in enclitic tokenization
- Fixed tokenizer test to reflect changes

Updates to Latin tokenizer

---

cltk/corpus/greek/beta_to_unicode.py

While I was working on using the betacode function to parse the Middle Liddell, I stumbled upon this speed increase.

Use compiled regex to sub. More than 10x faster.

---

docs/sanskrit.rst

There is a formatting bug in the Corpora section of Sanskrit docs where code is not formatted properly.This patch fixes it

Fix for formatting bug in Sanskrit docs

---

cltk/corpus/punjabi/corpora.py
cltk/corpus/punjabi/numerifier.py
cltk/corpus/utils/importer.py
cltk/tests/test_corpus.py

Applied suggestions, removed corpora.py, and removed its references from cltk/corpus/utils/importer.py, just undo every thing that is given in the wiki to add new corpus, changed from  `from cltk.corpus.punjabi.numerifier import * ` to `from cltk.corpus.punjabi.numerifier import <function name> ` both in test and numerifier file, removed the class NumericalMethods and added the tests to TestSequenceFunctions
Thats it may be it will be correct

Numerifier

---

cltk/corpus/latin/__init__.py
cltk/tokenize/sentence.py
cltk/tokenize/word.py

Three updates to fix these issues:
1. PlaintextCorpusReader now uses by default the Latin-specific sentence and word tokenizers.
In turn...
2. The sentence tokenizer has been updated to include a 'tokenize' method which PlaintextCorpusReader looks for in sentence tokenizers.
3. The word tokenizer for Latin now check for empty lists before checking the list indices.
In addition, the Latin-specific sentence tokenizer was causing tests to fail if CLTK_DATA was missing (or the right models from CLTK_DATA); point 1 above now checks for this model and if it is missing substitutes a generic NLTK sentence tokenizer.

Fixes #345 (& fixes #297) re: errors in Latinlibrary corpus loading methods

---

cltk/tests/test_corpus.py

We don't need import tests for all corpora, just one (and a few more if their data is used in succeeding unit tests).

Remove unnecessary corpus import tests (second try)

---

cltk/corpus/latin/__init__.py

Working to standardize case of 'cltk_data' when loading corpora and language models so that these calls do not fail on a case-sensitive filesystems.

Fixes #366; fix case of cltk_data

---

cltk/tokenize/latin_exceptions.py

This commit adds English words ending in '-n' to the list of exceptions for the Latin tokenizer; I have done this because corpora, spec. the Latin Library, contain English words that are currently being treated like Latin words by the tokenizer. This is not expected behavior and adds an unnecessary step to preprocessing. Since these are not valid Latin words, it should not lead to false negatives.

Add English words to exceptions list for Latin tokenizer

---

docs/greek.rst

[https://github.com/cltk/cltk/blob/master/docs/greek.rst](https://github.com/cltk/cltk/blob/master/docs/greek.rst) has been updated with information on the Greek alphabet and usage examples for [https://github.com/cltk/cltk/blob/master/cltk/corpus/greek/alphabet.py](https://github.com/cltk/cltk/blob/master/cltk/corpus/greek/alphabet.py)

Added documentation for Greek alphabet

---

docs/greek.rst

I hope this is condensed enough. I left out the functions `morae` and `contonation` since @jtauber said these are experimental in the original docs.

Documentation for jtauber's Greek Accentuation module

---

cltk/corpus/greek/alphabet.py
docs/egyptian.rst

Here is the PR dealing with the issues in #435 . Plus all the stuff i mentioned in the issue, once i printed the names of the characters in the original, i also noticed that the list named `UPPER_CONSONANTS` was a mess. It was a mix of latin characters with greek ones. Probably the author didn't check values with unicodedata before creating the list. Anyway it should all be good now.

Greek alphabet

---

.travis.yml
README.md
cltk/tests/test_utils.py
cltk/utils/file_operations.py
docs/installation.rst

Note that to make a virtual env now, you must do: `python -m venv <virt_env_name>`. Docs have been update to this.

Update proj to py3.6

---

cltk/tests/test_tokenize.py
cltk/tokenize/line.py
docs/latin.rst

New line tokenizer splits texts into a list of lines. This is designed for working with poetry and is meant to be a starting point for making line-based, as opposed to grammar-based, text operations easier (e.g. studying acrostics).

Add line tokenizer to CLTK

---

cltk/tests/test_tag.py
setup.py

Add `python-crfsuite` to install dependencies and add crf tagging test.

add python-crfsuite

---

cltk/corpus/greek/alphabet.py
cltk/tests/test_corpus.py

Hi, 
I have expanded the greek alphabet module, mentioned in now closed #435 . It now covers more rare characters, numerical signs, and accents, except the combining ones. I also added a filtering function, for filtering non-greek characters in a text. You can see the test in the relative section under your iota_expanded. With this PR, cltk would cover around 90 % of the ancient greek signs indicated in the unicode table. 
There are some greek symbols that I left out intentionally, because they are mostly used in mathematics rather than in literature or in philology. For example phi symbol is used in mathematics, but phi letter is used in philology. Both are included in the ancient greek section of the unicode and resemble each other a lot. I intentionally left out the phi symbol.

extended greek alphabet and added a filtering function

---

.gitignore
cltk/stem/akkadian/bound_form.py
cltk/stem/akkadian/cv_pattern.py
cltk/stem/akkadian/declension.py
cltk/stem/akkadian/stem.py
cltk/tests/test_stem.py

Still getting the hang of working with this material locally and pushing remotely.  Curious how the tests will fare.
This is a bunch of methods to work with Akkadian nouns.  The bound form and stemmer are both useful helper functions later on when working with suffixed pronouns.  The CV Pattern will be a useful function for verbs as well.
Finally the decliner is rather simple in constructions, but spits out a declined noun given any input form.  This can be used to both decliner nouns, and identify their form (by declining them and matching the form and reading its attributes).

Added methods for Akkadian nouns

---

docs/french.rst
docs/index.rst
setup.py

Corpora download correctly; ipython tests pass. 
Bumps version to 0.1.64; adds French to docs index; minor edits to docs more generally.

Fixes #574, French code check

---

.travis.yml

Please refer to commit message for details.
I did not test upload to PyPi.

Simplify CI by deleting redundant production of source distribution

---

cltk/corpus/old_norse/runes.py
cltk/phonology/utils.py
cltk/tests/test_corpus.py
docs/old_norse.rst

This is my pull request following #794. The runes retrieval method will be added in a specific repository.

Runes in ctlk core

---

.travis.yml

> 3.7 not available on default Ubuntu/travis builds, so using
instructions here: https://docs.travis-ci.com/user/languages/python/ to
update us to 3.7 (while keeping 3.6) and maybe later pre-release dev
builds

update travis to use xenial

---

cltk/corpus/latin/corpora.py
cltk/corpus/readers.py

CLTK Tesserae Ancient Greek Corpus & CLTK Tesserae Latin Corpus are now available in the CLTK GitHub repository (e.g. https://github.com/cltk/greek_text_tesserae). This PR makes the files (Latin specifically; Greek was in a previous PR) available to the corpus installer and the plaintext reader.

Update corpus files to include Tesserae corpora

---

cltk/tag/ner.py
cltk/tests/test_corpus/test_corpus.py

Removed failing doctest from cltk/tag/ner.py—should not affect anything since there is a redundant unit test.

Remove failing doctest; fixes #903

---

cltk/corpus/old_norse/syllabifier.py
cltk/corpus/punjabi/alphabet.py
cltk/phonology/gothic/transcription.py
cltk/phonology/middle_english/transcription.py
cltk/phonology/old_norse/transcription.py
cltk/phonology/old_swedish/transcription.py
cltk/phonology/orthophonology.py
cltk/phonology/utils.py
cltk/stem/sanskrit/indian_syllabifier.py
cltk/stop/middle_high_german/stops.py
cltk/stop/punjabi/stops.py
cltk/tests/test_akkadian/test_akkadian.py
cltk/tests/test_nlp/test_orthophonology.py
cltk/tests/test_nlp/test_semantics.py
cltk/tests/test_nlp/test_stem.py
cltk/text_reuse/comparison.py
cltk/tokenize/akkadian/word.py
cltk/tokenize/arabic/word.py
cltk/tokenize/middle_english/params.py
cltk/tokenize/middle_english/word.py
cltk/tokenize/middle_high_german/params.py
cltk/tokenize/middle_high_german/word.py
cltk/tokenize/old_french/params.py
cltk/tokenize/old_french/word.py
cltk/tokenize/old_norse/params.py
cltk/tokenize/sentence.py
cltk/tokenize/word.py
cltk/utils/contributors.py
cltk/utils/file_operations.py
contributors.md

When I approved the #910 pull request, I didn't see that there were typos in authors' names and email addresses.
So I fixed authors' email addresses for contributors.md. I alsoo modified contributors.py so that it may be run from a Unix or Windows OS. Finally, I changed some ''' into """ for docstrings.

Fixed authors' email addresses for contributors.md 

---

cltk/phonology/old_english/orthophonology.py
cltk/phonology/orthophonology.py
cltk/tests/test_nlp/test_orthophonology.py

This is mainly some reformatting of Python modules. I added a `geminate` function which may be useful for `Consonant` instances (like the `lengthen` method for `Vowel` instances).

Orthophonology reformatting

---

cltk/lemmatize/old_english/lemma.py
docs/old_english.rst

Fix for #930 
Also there's an evaluation function in the lemmatizer which is for dev purposes and can be ignored by end users.  Maybe it should live somewhere else?

added __init__.py for OE lemmatizer submodule

---

cltk/tokenize/word.py
docs/multilingual.rst

1. Simple pylint cleanup of the word.py file, plus logging a warning that `french` defaults to `old_french`.
2. I would like to point out the following pylint warnings coming out of the `BaseWordTokenizer`, and what if anything should be done about them:
```
$ pylint cltk/tokenize/word.py 
************* Module cltk.tokenize.word
cltk/tokenize/word.py:127:8: W0107: Unnecessary pass statement (unnecessary-pass)
cltk/tokenize/word.py:146:4: W0221: Parameters differ from overridden 'tokenize' method (arguments-differ)
cltk/tokenize/word.py:171:4: W0221: Parameters differ from overridden 'tokenize' method (arguments-differ)
cltk/tokenize/word.py:198:4: W0221: Parameters differ from overridden 'tokenize' method (arguments-differ)
```

Docs and formatting fixes for WordTokenizer

---

cltk/tests/test_nlp/test_tokenize.py
cltk/tokenize/latin/params.py
cltk/tokenize/latin/sentence.py
cltk/tokenize/sentence.py
docs/latin.rst

Adds a ```strict`` parameter to the Latin Punkt tokenizer that extends the list of punctuation used for sentence segmentation from period, question mark, and exclamation point to also include colon, semicolon, and hyphen. Includes test and docs. Fixes #943.

Add parameter for punctuation used by Latin punkt sentence tokenizer

---

.gitignore
cltk/corpus/greek/tlgu.py
docs/greek.rst

Following from my comment here, to the update of TLGU: https://github.com/cltk/greek_software_tlgu/issues/3#issuecomment-643819616
Everyone's code is OK, but am changing the method parameter `break_lines` to `rm_newlines`, which to me is less ambiguous.

Minor modification for TLGU

---

cltk/corpus/utils/formatter.py
cltk/tests/test_corpus/test_corpus.py
setup.py

Following up on #953 and the latest v1.8 of TLGU, which uses a new kind of pointed bracket to signify an editor's addition. Example taken from text number 1560, *Matthiae Traditiones*:
```
ἔστι γάρ, φησίν, ἐκεῖνο οὐχ ἁπλῶς ἄρρητον, 〈ὃ〉 ὀνομάζεται·
```
cc @pharos-alexandria you may want to re-run your TLG scripts with the latest version of TLGU

Update TLG cleanup with new angle bracket

---

Makefile
src/cltk/core/data_types.py
src/cltk/dependency/processes.py
src/cltk/morphology/morphosyntax.py
src/cltk/nlp.py
src/cltk/phonology/orthophonology.py
src/cltk/tag/pos.py
src/cltk/utils/utils.py

The `cltk.morphology.morphosyntax` module defines a long list of constants, represented as [Python enumerations](https://docs.python.org/3/library/enum.html), that represent *at least* the features and values published by the [Universal Dependencies](https://universaldependencies.org/) project.  
Stanza pipelines for the most part return words annotated with UD features (though this is treebank-dependent).  This PR: 
1.  transforms the strings of feature names and values returned by Stanza for each word to CLTK `MorphosyntacticFeature` objects;
2.  replaces POS string attributes with constants of the `POS` enumeration;
3.  adds a `category` attribute to `Word` objects, representing the part of speech of the word in terms of binary categorial features, F(unctional), N(ominal), V(erbal). …

Implement normalized representations of morphosyntactic features

---

src/cltk/tokenizers/akk.py
src/cltk/tokenizers/lat/lat.py
src/cltk/tokenizers/processes.py
src/cltk/tokenizers/word.py

I recently realized that `Word.index_char_start` and `Word.index_char_stop` were never set, so I added a method in WordTokenizer that computes them.

Added word indices

---

docs/installation.rst
notebooks/CLTK Demonstration.ipynb
pyproject.toml
src/cltk/morphology/morphosyntax.py

If fleeting on Livy text, don't know why. this should print and move on

print non-match of feature instead of error

---

docs/conf.py
src/cltk/dependency/processes.py
src/cltk/dependency/stanza.py
src/cltk/dependency/tree.py
src/cltk/morphology/morphosyntax.py
src/cltk/phonology/grc/transcription.py

Fixes the `fro` stanza pipeline to have depparses in it, so that we now get those in the CLTK `Words`.
The solution doesn't feel right to me, since we should be able to simply pass in the default `processors` argument to the Stanza constructor -- which works when using Stanza directly -- but so far this is the only way it's worked for me.
Also patches `DependencyTree` to make sure it doesn't crash when presented a sentence without dependencies.

fix for #1082

---

docs/pipelines.rst
docs/quickstart.rst

Fix broken links in docs/tutorials pointing to `dev` branch, it's now `master`

Correct broken doc links

---

src/cltk/lemmatize/grc.py
src/cltk/lemmatize/lat.py

Fixes #1051 issue about train/test split by replacing fixed slices applied to training sentences with a slice based on a 90%/10% split.
i.e.
```
train_size = int(.9 * len(train))
pos_train_sents = train[:train_size]
```
instead of
```
pos_train_sents = train[:4000]
```
Ensures all sentences are used, responds to changes in the underlying training data (i.e. if sentences were ever added, etc.) Applied to both the `lat` and `grc` backoff lemmatizers.

Fixes #1051 issue about train/test split

---

src/cltk/lemmatize/backoff.py
src/cltk/lemmatize/grc.py

Fix BackoffLemmatizer, treat empty strings as None.
Added doctest based on Issue 1051.
Treating empty strings as None seems reasonable; however a deeper review of the mappings is probably warranted.

Fix BackoffLemmatizer

---

src/cltk/morphology/morphosyntax.py
src/cltk/morphology/universal_dependencies_features.py

fixes: https://github.com/cltk/cltk/issues/1099
Proof:
```
% make shell                                                       
poetry run ipython --automagic
Python 3.8.3 (default, Jun 18 2020, 21:39:14) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: from cltk import NLP
In [2]: nlp=NLP(language='lat')
‎𐤀 CLTK version '1.0.11'.
Pipeline for language 'Latin' (ISO: 'lat'): `LatinNormalizeProcess`, `LatinStanzaProcess`, `LatinEmbeddingsProcess`, `StopsProcess`, `LatinNERProcess`, `LatinLexiconProcess`.
In [3]: doc = nlp("et hoc est quod dicitur ii petri 3-7:")
In [4]: quit()
```

add num form Reference for lat ittb compliance

---

docs/conf.py
poetry.lock
pyproject.toml
src/cltk/core/data_types.py
src/cltk/embeddings/processes.py
src/cltk/lemmatize/grc.py
src/cltk/lemmatize/lat.py
src/cltk/wordnet/wordnet.py

* Added SIF sentence embeddings, implementation based on https://openreview.net/pdf?id=SyK00v5xx and POC implementation at: https://github.com/todd-cook/ML-You-Can-Use/blob/master/quality_embeddings/sentence_similarities_seneca.ipynb 
* Added Sentence object to contain the sentence embedding, and did minor refactoring so that it be indexed as a list of a list of words--as before.
* Added bring-your-own word idf file/env name that can be swapped in to compute the embeddings.
* Added TFIDF mapping for cltk model directory for generic, canned tfidf mapping files.
* Added scikit-learn library for the PCA reduction of the embeddings.
* Corrected problematic doctest for Greek lemmatization.
* minor changes from formatting. 
Also depends on: https://github.com/cltk/lat_models_cltk/pull/9 …

add SIF Sentence embeddings

---

src/cltk/lexicon/lat.py

This PR fixes #1113 
Changes:
- Escape lemma before lookup to prevent process from failing on regex match when special characters (e.g. single parenthesis , i.e. '(' ) are passed to lookup
- Add doctests

Escape lemma before lookup in Lexicon process for Latin; fixes #1113

---

pyproject.toml
src/cltk/alphabet/text_normalization.py
src/cltk/sentence/sentence.py

Fix sentence tokenizer so that it can't be instantiated by itself (since it's a base class), minor corrections on initialization order and error handling.
change motivated by: https://github.com/cltk/cltk/issues/1120
This is the expected behavior:
```
% make shell
poetry run ipython --automagic
Python 3.8.3 (default, Jun 18 2020, 21:39:14) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.25.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: from cltk.sentence.sentence import PunktSentenceTokenizer
In [2]: toker = PunktSentenceTokenizer(language='LAT')
In [3]: toker.tokenize('quid est ueritas. uir qui adest.')
Out[3]: ['quid est ueritas.', 'uir qui adest.']
In [4]: from cltk.sentence.sentence import SentenceTokenizer
In [5]: sent_toker = …
```

Fix doctest and tokenizer

---

src/cltk/alphabet/grc/grc.py
tests/test_alphabet.py

- Switched order of `tonos_oxia_converter` and `cltk_normalize` in `normalize_grc` to address problems with the normalization process described in #1143 
- Added test

Fix normalization process as described in #1143; add test

---

src/cltk/tokenizers/lat/lat.py

Prevents hyphen from being added when separating 'ne' enclitics at sentence start.

Change ne enclitic handling; fixes #1145

---

poetry.lock
pyproject.toml

Original error while working in a notebook:
``` python
---------------------------------------------------------------------------
ContextualVersionConflict                 Traceback (most recent call last)
Input In [10], in <cell line: 1>()
----> 1 from cltk.corpora.grc.tlg.tlgu import TLGU
File ~/.pyenv/versions/3.10.5/envs/test_gpu/lib/python3.10/site-packages/cltk/__init__.py:7, in <module>
3 import pkg_resources
5 from .nlp import NLP
----> 7 __version__ = curr_version = pkg_resources.get_distribution(
8     "cltk"
9 )
File ~/.pyenv/versions/3.10.5/envs/test_gpu/lib/python3.10/site-packages/pkg_resources/__init__.py:466, in get_distribution(dist)
464     dist = Requirement.parse(dist)
465 if isinstance(dist, Requirement):
--> 466     dist = get_provider(dist)
467 if not …
```

update pyyaml to 6.0.0

---

src/cltk/morphology/morphosyntax.py

Added methods to `MorphosyntacticFeatureBundle` so that it looks more like a `dict`. It will help analyze more easily the morpho-syntactic features of words.

Improve MorphosyntacticFeatureBundle

---

src/cltk/prosody/lat/hendecasyllable_scanner.py
src/cltk/prosody/lat/hexameter_scanner.py
src/cltk/prosody/lat/pentameter_scanner.py

The Levenshtein distance is only 0 when the two strings are similar, so these calculations can be replaced with equivalence checks.

remove superfluous Levenshtein calculations

---

poetry.lock
pyproject.toml
src/cltk/embeddings/embeddings.py

fasttext has build problems. We are using gensim anyways, so I'm pretty sure it should not be a dependency, anyways.

rm fasttext

---

src/cltk/prosody/grc.py

Minor changes to the Scansion Module for Ancient Greek.
290-91 to
```
if (next_syll[0] in self.sing_cons and next_syll[1] in self.sing_cons) and (
next_syll[0] not in self.stops or next_syll[1] not in self.liquids)
```
to fix problems with mute/liquid detection
And also to fix the problem with repeated syllables in the same sentence
line 266 to:` def _long_by_position(self, sentence_index, syllable: str, sentence: list[str]) -> bool:`
288 to: `next_syll = sentence[sentence_index + 1]`
using the variable sentence_index to locate the syllable in question as a part of the function _long_by_position. The variable is set in the _scansion function.
324 to: `for i, syllable in enumerate(sentence):`
325 to: `if self._long_by_position(i, syllable, sentence) or self._long_by_nature(
`
These fairly …

Scansion adjustment, issue #1246
